### PR TITLE
Extended to the wider net

### PR DESCRIPTION
**Pull request by ekingery**
This plugin will now search for flattr'able urls anywhere on the net, as opposed to specific whitelisted sites. There are a couple of bug fixes, and a new barebones extension options page, where the level of recursion can be specified. The defaults can easily be changed within the code, and it would also be easy to add the concept of the whitelist back in as an option.

### CODE REVIEW

**Comment by leihog** [comment]
First of all, good work! I'm happy to see that we are getting contributions from our community. :)
I have one concern tho. I'm not so sure removing the whitelist is a good idea.
The whitelist served the purpose of not telling us about each url the user visited.
We don't do any data mining or logging of visited urls but even so there are a lot of people out there that would rather be safe than sorry (or just don't believe us when we say we don't).
At the very least the whitelist function should remain as an option, and preferably one that is activated by default.

**Comment by ekingery** [comment]
Thanks, my pleasure. Just to clarify, we're talking about protecting the user's host IP address (and any other HTTP headers sent by Chrome) from potentially being linked to the query urls received via the flattr API. I do understand the concern, especially for https pages where this info is not already sent in plaintext over the internet. One potentially mitigating factor: Chrome does not load extensions in incognito mode, so many people concerned about privacy will be covered by this (or other means).

Unfortunately the whitelist in it's current form drastically reduces the amount of flattrable sites the plugin will detect. I can think of two compromises. Let me know what you think about these:
1. Add a whitelist extension option which defaults to 'on' for all https pages, 'off' for http pages. This would expose no 'new' information about the user's browsing data, although technically it still allows flattr to more easily collect this data from a large chunk of users than traditional means (packet sniffing). 
2. Add a whitelist extension option, which defaults to 'on' for all pages. Add a flattr API call which would return the whitelist (this could be cached in local storage, or stored once per browser session as opposed to every request). This would eliminate the need to maintain a hard-coded list inside the plugin code and it would allow for easy expansion, etc..

**Comment by pthulin** [comment]
Hi Eric! Sorry for getting back on this so late.

Great stuff!

Here's some feedback on coding style:
1. Keep the original indentation level of 4 spaces.
2. Variables should beLikeThis
3. If-statements should be like this:

``` javascript
if (this) {
    thenThat();
}
```

And not like this:

``` javascript
if (this) thenThat();
```

I'll write this down into a proper style guide.

Other feedback:
1. I agree with the removal of the whitelist concept. I agree Chrome's incognito mode is sufficient and don't think this needs to be an option (if you look back in the commit history you can see that it was).
2. About the recursive function, my first reaction was that it could be misleading, e.g. I wanted to flattr github.com/ekingery and not github.com. But the more I think about it the more I like it... E.g. for github.com/ekingery/project/x it works great. Let's try it out :) As long as we view the flattr.com/thing/<id> page, that works as an extra confirmation step for the user.

Again, great work! Keep it up! I'll pull this as soon as the code style is ok!

**Comment by ekingery** [comment]
Thanks for the feedback! I'll clean up the coding style and hopefully push up another update this week. Yes, the recursion does start with the most specific page, then goes 'backwards', so github.com/username/ will always be searched for a flattr thing before github.com. It's nice because even for single domain sites, something like http://abc.com/freeservice/thing1 will allow the owner to have a specific flattr thing for that url, but also a 'catchall' thing on http://abc.com in case they have other general content they want to be flattrable. I especially like that a publisher does not even need to put the flattr button on their site if they create a flattr thing for the base domain. 

What do you think about the default recursion level of 5, and hard-coded limit of 10? I was thinking 5 is a reasonable default given that the calls are non blocking and executed like a queue (one completes before the next one starts). This is nice so the API does not get hammered with simultaneous requests from a single user.

**Comment by pthulin** [comment]
5 as default and 10 as max sounds reasonable.

**Comment by ekingery** [comment]
Okay, should be all set, let me know if there are any further issues. I tested it out and things look good. No functional changes made, just comments and tabs.

**Comment by pthulin** [comment]
Nice! One last thing: could you please squash the commits together so the diffs do not get unnecessarily big?

**Comment by ekingery** [comment]
Okay - should be ready for pull. Will you handle updating the chrome web store? I incremented the version in the manifest.json so it should be good to go.

**Comment by pthulin** [comment]
Cool, thanks. I've pulled this and will make a new release soon.

**Comment by pthulin** [comment]
Hm, options/index.html is lost now... Do you want me to add it back or do you want to have the honor? :)

**Comment by ekingery** [comment]
Oops, good catch! I just pushed it back up to my fork, but feel free to add yourself or do another pull / merge, whichever way is easier for you.

**Pull request merged**
